### PR TITLE
Update refs from old org/repo to new one

### LINKED ISSUE #4: Move this repo
... to jupyter-incubator.

### PR DESCRIPTION
**Pull request by parente**
Fixes #4

### CODE REVIEW

**Comment by parente** [comment]
@jtyberg Can you manually review the link changes? We should do one VM deployment after merging to make sure everything is working order before bringing up all the VMs.

**Comment by jtyberg** [comment]
All links verified.

**Comment by parente** [comment]
@jtyberg if you get a minute, can you fire up one VM and try the completed notebook just to make sure nothing is missed?

**Comment by jtyberg** [comment]
Everything is working fine.  I provisioned a VM and the notebook, dashboard server, and kernel gateway all came up.  I also went through the completed notebook.  Looks good.

**Pull request merged**
